image: ruby:2.7.0
services:
  - postgres:12.2-alpine

variables:
  RAILS_ENV: test
  POSTGRES_DB: deliver_app_test
  POSTGRES_USER: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_HOST: postgres

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - gem install bundler --no-document
  - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor

stages:
  - test
  - security_check
  - code_style_check
  - deploy

brakeman:
  stage: security_check
  script:
  - bundle exec brakeman

rubocop:
  stage: code_style_check
  script:
  - bundle exec rubocop

rspec:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - bundle install --path /cache
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rake test
  - bundle exec rspec

staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=delivery-app-env-staging --api-key=$HEROKU_APP_STAGING
  when: manual
